namespace OOP6;

class Program
{
    public static void ProcessTicket(Ticket ticket)
    {
        Console.WriteLine("==== Process Single Ticket ====");
        ticket.Print();
    }
    
    static void Main(string[] args)
    {
        // Part one questions are answered down there
        // Part two questions are answered in the whole project

        // Ticket ticketTest = new Ticket("AA", 22m);              Compiler Error
        Cinema cinema = new Cinema("Cinema Amir");
        cinema.OpenCinema();

        Ticket ticket1 = new StandardTicket("Inception", 120m, "2B");
        Ticket ticket2 = new VIPTicket("HarryPotter", 200m, true);
        Ticket ticket3 = new IMAXTicket("Batman", 300m, true);
        ticket1.Book();
        ticket2.Book();
        ticket3.Book();
        
        cinema.AddTicket(ticket1);
        cinema.AddTicket(ticket2);
        cinema.AddTicket(ticket3);

        cinema.Print();
        
        
        Console.WriteLine("==== Polymorphism ====");
        Console.WriteLine($"StandardTicket Final Price : {ticket1.SetPrice(ticket1.Price)}");
        Console.WriteLine($"VipTicket Final Price : {ticket2.SetPrice(ticket2.Price)}");
        Console.WriteLine($"IMAXTicket Final Price : {ticket3.SetPrice(ticket3.Price)}");
        
        Console.WriteLine("==== Extension Methods ===="); 
        ticket2.Receipt();
        Ticket[] tickets = new Ticket[] { ticket1, ticket2, ticket3 };
        tickets.TotalRevenue();

        cinema.CloseCinema();
    }

    #region Part1

    #region Q1

    // Abstraction is an is-A relation that is used to hide the complex data from the user and keeping them away,
    // Encapsulation is the way to have a control & a more secure data and gathering them into a single unit.
    // Real example : Elevator
    // when you enter an elevator then you press buttons you don't know how it really works this is Abstraction
    // the elevator have a single room that have its motors, boards only the technican can touch them this is Encapsulation.

    #endregion

    #region Q2

    // // Differences:
    // 1. Multiple Inheritance
    // 2. Default Implementation
    // 3. Fields and Constructors
    // 4. Access Modifiers
    //
    // When to choose which:
    // - Choose an Abstract Class when creating an Is-A relationship where child 
    //   classes share a core identity and you want them to inherit common shared code
    // - Choose an Interface when defining a Can-Do relation across completely unrelated classes

    #endregion
    
    #region Q3

    // 1- No because abstract class can't be instantiated, but you can create object in the child classes
    // 2- PowerConsumption is an abstract method that needs to be implemented, status can be overriden, label is made to be called only
    //    the abstract one is made to be implemented when the child inherits 
    //    the virtual one have a default implementation but it can be overriden with any other functionality
    //    the concrete one should be called without any edits on it.
    // 3- will output "Standby" because its the default implementation and there is no override on it in toaster
    
    #endregion
    
    #region Q4

    // 1- Partial class is a class that completes another class but in another file, you can split it into two files
    //    because of having an autogenerated code, or to complete a code without editing the original file.
    // 2- Partial method is a method that implements or completes the original method in the original partial class
    //    The code will still compile normally, it will search for an implementation if not found it ignores the whole method
    // 3- Extension methods are methods that allows you to add new methods to an already made file like microsoft
    //    files without touching the original file
    //    Rules: 1-should be inside static class
    //           2-the method should be static
    //           3-should use this keyword
    // 4- Log: result = 20, then $20.00
    
    #endregion
    
    #endregion
}